//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Planner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Room_Planner.Properties.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双人床.
        /// </summary>
        internal static string bed {
            get {
                return ResourceManager.GetString("bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咖啡桌.
        /// </summary>
        internal static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咖啡桌.
        /// </summary>
        internal static string coffee_table {
            get {
                return ResourceManager.GetString("coffee_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双人床.
        /// </summary>
        internal static string double_bed {
            get {
                return ResourceManager.GetString("double_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取蓝图.
        /// </summary>
        internal static string Load_blueprint {
            get {
                return ResourceManager.GetString("Load_blueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建蓝图.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存蓝图.
        /// </summary>
        internal static string Save_blueprint {
            get {
                return ResourceManager.GetString("Save_blueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沙发.
        /// </summary>
        internal static string sofa {
            get {
                return ResourceManager.GetString("sofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桌子.
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 墙.
        /// </summary>
        internal static string wall {
            get {
                return ResourceManager.GetString("wall", resourceCulture);
            }
        }
    }
}
